services:

  #
  # Command
  #
  Basilicom\AreabrickReport\Command\AreabrickReportDataCommand:
    arguments:
      $areabrickManager: '@Pimcore\Extension\Document\Areabrick\AreabrickManager'
      $connection: '@doctrine.dbal.default_connection'
    tags: [ 'console.command' ]
