services:
  #
  # Custom Reports
  #
  basilicom.areabrick_report.custom_report.adapter.factory:
    class: Basilicom\AreabrickReport\CustomReport\AreabricksReportAdapterFactory
    arguments:
      - 'Basilicom\AreabrickReport\CustomReport\Areabricks'
      - '@Pimcore\Extension\Document\Areabrick\AreabrickManager'
      - '@doctrine.dbal.default_connection'

  Pimcore\Extension\Document\Areabrick\AreabrickManager: ~

  #
  # EventListener
  #
  Basilicom\AreabrickReport\EventListener\PimcoreAdminEventListener:
    tags:
      - { name: kernel.event_listener, event: pimcore.bundle_manager.paths.js, method: addAdminJSFiles }
