pimcore_custom_reports:
  definitions:
    areabricks:
      name: areabricks
      sql: ''
      dataSourceConfig:
        -
          sql: '*'
          from: areabrick_report
          where: ''
          groupby: ''
          orderby: documentPathKey
          orderbydir: ASC
          type: sql
      columnConfiguration:
        -
          name: id
          display: false
          export: true
          order: true
          width: 80
          label: 'Id'
          id: extModel726-1
        -
          name: areabrickName
          display: true
          export: true
          order: true
          width: 200
          label: 'Areabrick'
          displayType: text
          filter_drilldown: filter_and_show
          filter: string
          id: extModel726-2
        -
          name: areabrickId
          display: false
          export: true
          order: true
          width: 200
          label: 'Areabrick Id'
          filter: string
          id: extModel726-3
        -
          name: areabrickIndex
          display: true
          export: true
          order: true
          width: 50
          label: 'Index'
          filter: number
          id: extModel726-4
        -
          name: documentTitle
          display: true
          export: true
          order: true
          width: 200
          label: 'Document Title'
          displayType: text
          filter_drilldown: filter_and_show
          filter: string
          id: extModel726-5
        -
          name: documentPathKey
          display: true
          export: true
          order: true
          width: ''
          label: 'Document Path'
          displayType: text
          filter: string
          id: extModel726-6
        -
          name: documentType
          display: true
          export: true
          order: true
          width: 100
          label: 'Document Type'
          displayType: text
          filter: string
          id: extModel726-7
        -
          name: documentLanguage
          display: true
          export: true
          order: true
          width: 80
          label: 'Language'
          displayType: text
          filter_drilldown: filter_and_show
          filter: string
          id: extModel726-8
        -
          name: documentId
          display: false
          export: true
          order: true
          width: 80
          label: 'Document Id'
          filter: number
          columnAction: openDocument
          id: extModel726-9
      niceName: Areabrick
      group: ''
      groupIconClass: ''
      iconClass: ''
      menuShortcut: false
      reportClass: ''
      chartType: ''
      pieColumn: null
      pieLabelColumn: null
      xAxis: null
      yAxis: {  }
      modificationDate: 1742227972
      creationDate: 1742227758
      shareGlobally: true
      sharedUserNames: {  }
      sharedRoleNames: {  }
